version: '3'
services:
  web:
    image: snowstormkitten/minecraftservertest
    ports:
      - "25565:25565"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
      mode: replicated
      replicas: 1